menu:
  文章: /articles
  归档: /archives
  分类: /categories
  活动: /activity
  关于: /about

# 文章计数（需要hexo-symbols-count-time插件）

# 主页
frontpage:
  # 主页banner
  banner:
    # 是否开启banner
    enable: true

    # banner头像图片
    avatar: img/logo.png
    # banner标题
    title: word-card
    # banner副标题
    motto: 一个简洁、优雅、阅读向的hexo主题

    # 动态一言
    hitokoto:
      # 是否开启动态一言
      enable: true

      # 一言api
      hitokoto_url: https://v1.hitokoto.cn/

      # 自定义一言展示内容，开启后优先级高于一言api
      custom: false
      # 自定义一言文件链接
      # 可以参考json目录下的示例文件
      custom_url: json/hitokoto.json
      # 点击区域跳转链接
      custom_link: /

  # 主页内容
  main:
    # 主页介绍区
    introduction:
      # 是否开启
      enable: true

      # 展示区内容表
      intro: [
          # 想增加条目，复制下方内容并在intro下重复即可
          # 内容开始
          {
            # 图片链接
            img: /img/logo.png,
            # 标题
            title: word-card,
            # 描述文本
            text: 一个简洁、优雅、阅读向的hexo主题,
            # 链接
            link: /about,
            # 链接文本
            link_text: 了解更多,
            # 是否在新标签页打开链接
            blank_target: false,
          },
          # 内容结束
          {
            img: /img/logo.png,
            title: word-card,
            text: 一个简洁、优雅、阅读向的hexo主题,
            link: /about,
            link_text: 了解更多,
            blank_target: false,
          },
        ]

# 页脚内容
footer:
  icp:
    # 是否开启
    enable: true
    # ICP备案号
    id: XICP备xxxx号

  beian:
    # 是否开启
    enable: true
    # 公安备案号
    id: X公网安备xxxxx号

  copyright:
    year: 2021

  custom_link:
    # 是否开启
    enable: true
    # 自定义链接文本
    text: 欢迎访问主题仓库
    # 自定义链接
    link: https://github.com/kankezhiyan/word-card-hexo

  custom_text:
    # 是否开启
    enable: true
    # 自定义文本
    text: 感谢使用该主题

  # 如果使用主题默认背景图片，请保持开启
  bg_info:
    # 是否开启
    enable: true
    

# 类目/标签大于这个数量时，将自动折叠
max_items_each: 3
